// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductCrud.Persistence;

#nullable disable

namespace ProductCrud.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductCrud.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("ManufactureEmail")
                        .HasColumnType("varchar(254)");

                    b.Property<string>("ManufacturePhone")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ProduceDate")
                        .HasColumnType("DateTime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "system",
                            IsAvailable = true,
                            ManufactureEmail = "info.us@breitling.com",
                            ManufacturePhone = "+989112223334",
                            Name = "Breitling Watch, Top Time B01 Triumph",
                            ProduceDate = new DateTime(2022, 6, 26, 17, 50, 5, 672, DateTimeKind.Local).AddTicks(9809)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "system",
                            IsAvailable = false,
                            ManufactureEmail = "info.us@breitling.com",
                            ManufacturePhone = "+989112223334",
                            Name = "Breitling Watch, Top Time B01 Ford ThunderBird",
                            ProduceDate = new DateTime(2021, 6, 26, 17, 50, 5, 672, DateTimeKind.Local).AddTicks(9826)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "admin",
                            IsAvailable = true,
                            ManufactureEmail = "customercare@us.alpinawathes.com",
                            ManufacturePhone = "+19994445556",
                            Name = "Alpiner Watch, Heritage Carrée Mechanical 140 Years",
                            ProduceDate = new DateTime(2020, 6, 26, 17, 50, 5, 672, DateTimeKind.Local).AddTicks(9828)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
